### ISSUE TITLE
Task lists doubled after system crash

### ISSUE THREAD

**Issue by biolauri** [dmfs/tasks#140] opened 2015-05-29 01:32 UTC
First of all: Thanks for the great app! :+1: 

## Prologue
A few days ago, my Nexus 4 with Android 5.1 rebootet automatically into Safe Mode. After another reboot to get back to normal operations, all my custom (non-Google) accounts and widgets were gone (including CalDAV account to sync my calendar and task list). It seems that Safe Mode deletes 3rd party widgets and accounts rather than deactivating them while in Safe Mode.

According to the thread [Accounts/widgets lost in safe mode](http://forum.xda-developers.com/showthread.php?t=2364444) on the XDA Forums, this is a known bug (at least I'm not the only one). And this problem is easy to solve: Just re-add the accounts and the widgets and everything is restored.

## The actual problem
Before restoring it, I noticed that all the tasks are still in the Tasks app (contrary to the calendar events).

After restoring the accounts, I checked this and all task lists in the app are doubly present (even in the activity **Synchronized Lists**). Hence, all tasks are listed twice, too (in every view). Even if I deactivate (unselect) **all** lists, the *old* tasks are still listed (only the first view, where all tasks are grouped by list, is empty).

I thought this is a caching problem and get solved after a while, but the old tasks are still visible (and editable). I even pressed a few times `reload` and restartet my Nexus.

## Side note
While readding my caldav account, I selected new and different colors. But I don't think, this is relevant.

**Comment by dmfs** [comment] 2015-05-29 08:18
Thanks for the report. I think I know what happened:

When the device enters safe mode, all user-installed apps are disabled. That also means, they are not available as authenticators, which is why all their accounts get removed (that's the actual bug).

Apps like the calendar storage app, the contacts storage app or our task app listen for the "account removed" event and remove all stale resources (i.e. events, contacts and tasks that belonged to that account). However, since the task app was disabled in safe-mode it didn't receive that event and could not sanitize the database.
On the next regular reboot the event was not resent (of course) and the app didn't notice that accounts have been removed. So the stale task lists were still present.

When you recreated the CalDAV account, the app didn't check for exiting task lists, because it assumed there are none (since it just created the account) and created them again.

I think the best solution is to let the task app check on boot if all accounts are still present and run the cleanup code if not. Actually, I was under the impression we already do that, but apparently we don't.

**Comment by dmfs** [comment] 2015-05-29 08:19
Since the actual bug is in Android I'm labeling this as an enhancement, not as a bug.

**Comment by biolauri** [comment] 2015-05-29 10:06
Your explanation rings very true! Thanks for the immediate answer and for implementing this clean-up on boot check. :)

---

In addition, I had a weird behavior while doing my workaround for this problem: I re-installed the tasks app, so all stale tasks & lists were gone. But the task app didn't import the lists from my new created account, so I had to re-add the syncing account again.
I would not rule, this is a problem at my end. So shall I file another bug?

Just to be sure I explained the order correct:

1. I first re-added my sync account
2. Then I re-installed the tasks app to wipe out stale lists
3. I had to re-add my sync account again, because the tasks app didn't import it while re-installation
4. Now, all works fine! :)

**Comment by dmfs** [comment] 2015-05-29 14:35
Yeah, that's another issue that appears to be some kind of Android issue.

Here is what happens:

When the task app is installed for the first time, an initialization routine is called for every existing CalDAV account. During that initialization, the account is set up for task sync. The same happens when an account is created after the task app was installed.

The problem is: when you uninstall the task app and re-install it, the initialization routine is **not** re-run for the existing accounts. So tasks are not automatically configured to sync. You can, however, open CalDAV-Sync and go to "Select calendars to sync". That should bring back the task lists.

At present I've no idea how to fix this.

**Comment by dmfs** [comment] 2015-07-02 11:04
The duplicate lists issue should be fixed with the next release. The app now removes orphaned lists during boot, if their account has been removed while booting into safe mode.

**Closed by dmfs** 2015-07-02 11:04 UTC
Labels: enhancement

**Comment by biolauri** [comment] 2015-07-03 07:26
Great! :+1:
