### ISSUE TITLE
Problems syncing tasks from phone to Mykolab

### ISSUE THREAD

**Issue by tomtroughton** [dmfs/tasks#74] opened 2014-05-26 16:47 UTC
Hi,

I'm using tasks with CalDAV-Sync to connect to my Mykolab account. 2 issues when I add a task on the phone, and it gets synced to the server:

1. The app doesn't correctly send the time due - on the phone it is due for 17:00, on the server it is marked as 'All day'.

2. The app is adding '\' (escape character?) before commas in the title that appears when it is synced with my upstream account. So on the phone it says 'Phone charger, rent, mud window', while on the server 'Phone charger\, rent\, mud window'. 

This doesn't seem to be an issue when syncing the phone with tasks added to the server through Kontact on Kubuntu. Haven't tried with Windows yet.

I'm using Android 2.3.3 on a Samsung GT-I9000M, Tasks 1.0.11, and CalDAV-Sync 0.4.11.

Best wishes, Tom

**Comment by dmfs** [comment] 2015-03-10 10:40
Closing this one. Looks like it's fixed in Kolab and not a bug in this app anyway.

**Closed by dmfs** 2015-03-10 10:40 UTC
